# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#0f1511" # Color de fondo por defecto.
foreground = "#dfe4dd" # Color del texto por defecto.
cursor_bg = "#90d5ad"
cursor_border = "#c0c9c1"
cursor_fg = "#dfe4dd"

selection_bg = "#0b1f15"
selection_fg = "#203529"

scrollbar_thumb = "#dfe4dd"  # Color de la barra de desplazamiento.

split = "#404943" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#90d5ad",
    "#266a4a",
    "#90d5ad",
    "#a4cddd",
    "#b4ccbb",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
