# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#101418" # Color de fondo por defecto.
foreground = "#e0e2e8" # Color del texto por defecto.
cursor_bg = "#99ccfa"
cursor_border = "#c2c7ce"
cursor_fg = "#e0e2e8"

selection_bg = "#0d1d2a"
selection_fg = "#23323f"

scrollbar_thumb = "#e0e2e8"  # Color de la barra de desplazamiento.

split = "#42474e" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#99ccfa",
    "#2c638b",
    "#99ccfa",
    "#d2bfe7",
    "#b8c8da",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
