# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#121318" # Color de fondo por defecto.
foreground = "#e3e1e9" # Color del texto por defecto.
cursor_bg = "#b8c4ff"
cursor_border = "#c6c5d0"
cursor_fg = "#e3e1e9"

selection_bg = "#171b2c"
selection_fg = "#2c2f42"

scrollbar_thumb = "#e3e1e9"  # Color de la barra de desplazamiento.

split = "#45464f" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#b8c4ff",
    "#4f5b92",
    "#b8c4ff",
    "#e4bad9",
    "#c2c5dd",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
